### ISSUE TITLE
Respring on homescreen wallpaper change

### ISSUE THREAD

**Issue by marcodallagatta** [Karimo299/LeaveMeAlone#2]
After a few minutes after I change my homescreen wallpaper and pull-up the control center the my SE resprings. Cr4shed curiously doesn't even notice a crash, the phone just goes into safe mode. When I respring the wallpaper is pure black (even tho it still show the correct one in the Setting's preview), and everything works fine until I change the wallpaper again.

**Comment by Karimo299** [comment]
what iOS?

**Comment by marcodallagatta** [comment]
iPhone SE, 12.1.2.

**Comment by Karimo299** [comment]
Not sure if this issue is fixed in the new version, because I can't replicate it

**Comment by marcodallagatta** [comment]
> Not sure if this issue is fixed in the new version, because I can't replicate it

I've been using the latest version for a couple of days and the bug is gone, thanks Karimo!

**Comment by Karimo299** [comment]
Anytime! :)
